apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-05-22T00:54:29Z"
  name: backend
  namespace: default
  resourceVersion: "72141"
  uid: 82fa02f9-76d3-4567-a7a1-6d53639ebcf1
spec:
  clusterIP: 10.43.93.184
  clusterIPs:
  - 10.43.93.184
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30090
    port: 8089
    protocol: TCP
    targetPort: 8089
  selector:
    app: backend
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
