apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"frontend-service","namespace":"default"},"spec":{"ports":[{"nodePort":30081,"port":80,"targetPort":80}],"selector":{"app":"frontend"},"type":"NodePort"}}
  creationTimestamp: "2026-04-24T09:40:20Z"
  name: frontend-service
  namespace: default
  resourceVersion: "4299"
  uid: f64692e7-28f9-4019-b184-c97bdfe7452e
spec:
  clusterIP: 10.43.200.255
  clusterIPs:
  - 10.43.200.255
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30081
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
